# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-29 19:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyFantasySportsSite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='DailyFantasySportsSiteLeaguePosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_fantasy_sports_site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.DailyFantasySportsSite')),
            ],
        ),
        migrations.CreateModel(
            name='DailyFantasySportsSiteLeaguePositionGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_identifier', models.IntegerField(null=True)),
                ('daily_fantasy_sports_site_league_position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.DailyFantasySportsSiteLeaguePosition')),
            ],
        ),
        migrations.CreateModel(
            name='DailyFantasySportsSitePlayerGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary', models.DecimalField(decimal_places=2, max_digits=20)),
                ('site_name', models.CharField(max_length=250)),
                ('daily_fantasy_sports_site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.DailyFantasySportsSite')),
            ],
        ),
        migrations.CreateModel(
            name='DailyFantasySportsSitePlayerGamePosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_fantasy_sports_site_league_position_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.DailyFantasySportsSiteLeaguePositionGroup')),
                ('daily_fantasy_sports_site_player_game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.DailyFantasySportsSitePlayerGame')),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('identifier', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='LeaguePosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.League')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('identifier', models.CharField(max_length=50)),
                ('jersey', models.BigIntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.League')),
            ],
        ),
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.League')),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='data.Team'),
        ),
        migrations.AddField(
            model_name='leagueposition',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Position'),
        ),
        migrations.AddField(
            model_name='league',
            name='sport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Sport'),
        ),
        migrations.AddField(
            model_name='game',
            name='away_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_team', to='data.Team'),
        ),
        migrations.AddField(
            model_name='game',
            name='home_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_team', to='data.Team'),
        ),
        migrations.AddField(
            model_name='game',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='season', to='data.Season'),
        ),
        migrations.AddField(
            model_name='dailyfantasysportssiteplayergame',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Game'),
        ),
        migrations.AddField(
            model_name='dailyfantasysportssiteplayergame',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Player'),
        ),
        migrations.AddField(
            model_name='dailyfantasysportssiteleagueposition',
            name='league_position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.LeaguePosition'),
        ),
        migrations.AlterUniqueTogether(
            name='team',
            unique_together=set([('league', 'name')]),
        ),
        migrations.AlterUniqueTogether(
            name='season',
            unique_together=set([('league', 'start_time', 'end_time')]),
        ),
        migrations.AlterUniqueTogether(
            name='player',
            unique_together=set([('team', 'identifier', 'jersey')]),
        ),
        migrations.AlterUniqueTogether(
            name='leagueposition',
            unique_together=set([('league', 'position')]),
        ),
        migrations.AlterUniqueTogether(
            name='league',
            unique_together=set([('sport', 'name')]),
        ),
        migrations.AlterUniqueTogether(
            name='game',
            unique_together=set([('home_team', 'away_team', 'season', 'start_time')]),
        ),
        migrations.AlterUniqueTogether(
            name='dailyfantasysportssiteplayergameposition',
            unique_together=set([('daily_fantasy_sports_site_player_game', 'daily_fantasy_sports_site_league_position_group')]),
        ),
        migrations.AlterUniqueTogether(
            name='dailyfantasysportssiteplayergame',
            unique_together=set([('daily_fantasy_sports_site', 'player', 'game')]),
        ),
        migrations.AlterUniqueTogether(
            name='dailyfantasysportssiteleaguepositiongroup',
            unique_together=set([('daily_fantasy_sports_site_league_position', 'site_identifier')]),
        ),
        migrations.AlterUniqueTogether(
            name='dailyfantasysportssiteleagueposition',
            unique_together=set([('daily_fantasy_sports_site', 'league_position')]),
        ),
    ]
