# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-16 05:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dailyfantasysportssiteleagueposition',
            old_name='site_identifier',
            new_name='identifier',
        ),
        migrations.AlterUniqueTogether(
            name='dailyfantasysportssiteleagueposition',
            unique_together=set([('daily_fantasy_sports_site', 'league_position', 'identifier')]),
        ),
    ]
