# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-23 05:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyfantasysportssiteleaguepositiongroup',
            name='identifier',
            field=models.IntegerField(null=True),
        ),
    ]
