# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-07 06:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('data', '0002_auto_20170207_0606'),
    ]

    operations = [
        migrations.CreateModel(
            name='GamePlayerBoxScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=100)),
                ('explanation', models.CharField(default=None, max_length=100)),
                ('game_player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.GamePlayer')),
            ],
        ),
    ]
