# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-09 06:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nba_persistence', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameplayerboxscore',
            name='explanation',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
