# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-09 06:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nba_persistence', '0002_auto_20170209_0639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameplayerboxscore',
            name='assists',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='gameplayerboxscore',
            name='blocks',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='gameplayerboxscore',
            name='defensive_rebounds',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='gameplayerboxscore',
            name='field_goals_attempted',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='gameplayerboxscore',
            name='field_goals_made',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='gameplayerboxscore',
            name='free_throws_attempted',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='gameplayerboxscore',
            name='free_throws_made',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='gameplayerboxscore',
            name='offensive_rebounds',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='gameplayerboxscore',
            name='personal_fouls',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='gameplayerboxscore',
            name='plus_minus',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='gameplayerboxscore',
            name='seconds_played',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='gameplayerboxscore',
            name='steals',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='gameplayerboxscore',
            name='three_point_field_goals_attempted',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='gameplayerboxscore',
            name='three_point_field_goals_made',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='gameplayerboxscore',
            name='turnovers',
            field=models.BigIntegerField(null=True),
        ),
    ]
