# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-29 20:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyFantasySportsSite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='DailyFantasySportsSiteLeaguePosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_fantasy_sports_site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dfs_site_persistence.DailyFantasySportsSite')),
                ('league_position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.LeaguePosition')),
            ],
        ),
        migrations.CreateModel(
            name='DailyFantasySportsSiteLeaguePositionGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_identifier', models.IntegerField(null=True)),
                ('daily_fantasy_sports_site_league_position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dfs_site_persistence.DailyFantasySportsSiteLeaguePosition')),
            ],
        ),
        migrations.CreateModel(
            name='DailyFantasySportsSitePlayerGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary', models.DecimalField(decimal_places=2, max_digits=20)),
                ('site_name', models.CharField(max_length=250)),
                ('daily_fantasy_sports_site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dfs_site_persistence.DailyFantasySportsSite')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Game')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Player')),
            ],
        ),
        migrations.CreateModel(
            name='DailyFantasySportsSitePlayerGamePosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_fantasy_sports_site_league_position_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dfs_site_persistence.DailyFantasySportsSiteLeaguePositionGroup')),
                ('daily_fantasy_sports_site_player_game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dfs_site_persistence.DailyFantasySportsSitePlayerGame')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='dailyfantasysportssiteplayergameposition',
            unique_together=set([('daily_fantasy_sports_site_player_game', 'daily_fantasy_sports_site_league_position_group')]),
        ),
        migrations.AlterUniqueTogether(
            name='dailyfantasysportssiteplayergame',
            unique_together=set([('daily_fantasy_sports_site', 'player', 'game')]),
        ),
        migrations.AlterUniqueTogether(
            name='dailyfantasysportssiteleaguepositiongroup',
            unique_together=set([('daily_fantasy_sports_site_league_position', 'site_identifier')]),
        ),
        migrations.AlterUniqueTogether(
            name='dailyfantasysportssiteleagueposition',
            unique_together=set([('daily_fantasy_sports_site', 'league_position')]),
        ),
    ]
